<?php
/**
 * Payment page template — displays crypto payment options, QR code, amount, timer, and status.
 *
 * This template can be overridden by copying it to yourtheme/mycryptocoin-gateway/payment-page.php.
 *
 * @package MyCryptoCoin_Gateway
 * @version 1.0.0
 *
 * @var WC_Order $order           The WooCommerce order.
 * @var string   $payment_id      MyCryptoCoin payment ID.
 * @var string   $session_id      Payment session ID.
 * @var string   $crypto          Selected cryptocurrency slug.
 * @var string   $crypto_label    Human-readable crypto name.
 * @var string   $crypto_amount   Amount in cryptocurrency.
 * @var string   $payment_address Wallet address for payment.
 * @var string   $expires_at      Expiration timestamp (ISO 8601).
 * @var string   $status          Current payment status.
 * @var string   $return_url      URL to redirect after successful payment.
 */

defined( 'ABSPATH' ) || exit;

$is_test_mode = 'yes' === $order->get_meta( '_mycryptocoin_test_mode' );
?>

<?php do_action( 'mycryptocoin_before_payment_page', $order ); ?>

<div class="mycryptocoin-payment-page"
	data-session-id="<?php echo esc_attr( $session_id ); ?>"
	data-expires-at="<?php echo esc_attr( $expires_at ); ?>"
	data-return-url="<?php echo esc_url( $return_url ); ?>">

	<?php if ( $is_test_mode ) : ?>
		<div class="mycryptocoin-admin-notice mycryptocoin-admin-notice--test" style="text-align:left;margin-bottom:20px;">
			<p><strong><?php esc_html_e( 'Test Mode', 'mycryptocoin-gateway' ); ?></strong> &mdash; <?php esc_html_e( 'This is a simulated payment. No real crypto will be transferred.', 'mycryptocoin-gateway' ); ?></p>
		</div>
	<?php endif; ?>

	<div class="mycryptocoin-payment-page__header">
		<h2><?php esc_html_e( 'Complete Your Crypto Payment', 'mycryptocoin-gateway' ); ?></h2>
		<p>
			<?php
			printf(
				/* translators: %s: Order number */
				esc_html__( 'Order #%s', 'mycryptocoin-gateway' ),
				esc_html( $order->get_order_number() )
			);
			?>
		</p>
	</div>

	<div class="mycryptocoin-payment-page__amount">
		<?php echo esc_html( $crypto_amount ); ?> <?php echo esc_html( strtoupper( $crypto ) ); ?>
		<small>
			<?php
			printf(
				/* translators: %s: Fiat amount with currency */
				esc_html__( '(%s)', 'mycryptocoin-gateway' ),
				wp_kses_post( $order->get_formatted_order_total() )
			);
			?>
		</small>
	</div>

	<?php if ( ! empty( $payment_address ) ) : ?>
		<div class="mycryptocoin-qr-container"
			data-address="<?php echo esc_attr( $payment_address ); ?>"
			data-crypto="<?php echo esc_attr( $crypto ); ?>"
			data-amount="<?php echo esc_attr( $crypto_amount ); ?>">
			<!-- QR code will be generated by JavaScript -->
			<noscript>
				<p><?php esc_html_e( 'Please enable JavaScript to display the payment QR code, or copy the address below.', 'mycryptocoin-gateway' ); ?></p>
			</noscript>
		</div>

		<div class="mycryptocoin-address">
			<div class="mycryptocoin-address__label">
				<?php
				printf(
					/* translators: %s: Crypto name */
					esc_html__( 'Send %s to this address:', 'mycryptocoin-gateway' ),
					esc_html( $crypto_label )
				);
				?>
			</div>
			<div class="mycryptocoin-address__value">
				<code><?php echo esc_html( $payment_address ); ?></code>
				<button type="button" class="mycryptocoin-address__copy">
					<?php esc_html_e( 'Copy', 'mycryptocoin-gateway' ); ?>
				</button>
			</div>
		</div>
	<?php endif; ?>

	<?php if ( ! empty( $expires_at ) ) : ?>
		<div class="mycryptocoin-timer" data-expires="<?php echo esc_attr( $expires_at ); ?>">
			<span class="mycryptocoin-timer__icon">&#9203;</span>
			<span><?php esc_html_e( 'Calculating time remaining...', 'mycryptocoin-gateway' ); ?></span>
		</div>
	<?php endif; ?>

	<div class="mycryptocoin-status mycryptocoin-status--<?php echo esc_attr( $status ); ?>">
		<?php if ( 'pending' === $status || 'confirming' === $status ) : ?>
			<span class="mycryptocoin-spinner"></span>
		<?php endif; ?>
		<span>
			<?php
			$status_labels = array(
				'pending'    => __( 'Waiting for payment...', 'mycryptocoin-gateway' ),
				'confirming' => __( 'Payment detected, confirming...', 'mycryptocoin-gateway' ),
				'confirmed'  => __( 'Payment confirmed!', 'mycryptocoin-gateway' ),
				'failed'     => __( 'Payment failed', 'mycryptocoin-gateway' ),
				'expired'    => __( 'Payment expired', 'mycryptocoin-gateway' ),
			);
			$status_text = isset( $status_labels[ $status ] ) ? $status_labels[ $status ] : esc_html( $status );
			echo esc_html( $status_text );
			?>
		</span>
	</div>

	<div class="mycryptocoin-payment-page__footer" style="margin-top:24px;">
		<p style="font-size:13px;color:#718096;">
			<?php esc_html_e( 'Send the exact amount shown above. The payment will be detected automatically.', 'mycryptocoin-gateway' ); ?>
		</p>
		<p style="font-size:12px;color:#a0aec0;">
			<?php
			echo wp_kses_post(
				sprintf(
					/* translators: %s: MyCryptoCoin link */
					__( 'Secured by %s', 'mycryptocoin-gateway' ),
					'<a href="https://mycrypto.co.in" target="_blank" rel="noopener noreferrer" style="color:#6c5ce7;">MyCryptoCoin</a>'
				)
			);
			?>
		</p>
	</div>

</div>

<?php do_action( 'mycryptocoin_after_payment_page', $order ); ?>
