import { CryptoNetwork, TokenSymbol } from '@mycryptocoin/shared';

// Re-export shared types
export { CryptoNetwork, TokenSymbol };

/**
 * Backward-compatible CryptoSymbol enum.
 * Legacy code (crypto.service, wallet.service, etc.) uses CryptoSymbol.BTC style.
 * Each value matches a CryptoKey so `SUPPORTED_CRYPTOS[CryptoSymbol.BTC]` works.
 */
export enum CryptoSymbol {
  BTC = 'BITCOIN:BTC',
  ETH = 'ETHEREUM:ETH',
  USDT_ERC20 = 'ETHEREUM:USDT',
  USDC_ERC20 = 'ETHEREUM:USDC',
  DAI_ERC20 = 'ETHEREUM:DAI',
  USDT_TRC20 = 'TRON:USDT',
  TRX = 'TRON:TRX',
  BNB = 'BSC:BNB',
  SOL = 'SOLANA:SOL',
  LTC = 'LITECOIN:LTC',
  MATIC = 'POLYGON:MATIC',
  DOGE = 'DOGECOIN:DOGE',
  XRP = 'XRPL:XRP',
  XMR = 'MONERO:XMR',
  AVAX = 'AVALANCHE:AVAX',
  DOT = 'POLKADOT:DOT',
  ZEC = 'ZCASH:ZEC',
  BCH = 'BITCOIN_CASH:BCH',
  ADA = 'CARDANO:ADA',
  ARB_ETH = 'ARBITRUM:ETH',
  OP_ETH = 'OPTIMISM:ETH',
  BASE_ETH = 'BASE:ETH',
  ARB_USDC = 'ARBITRUM:USDC',
  OP_USDC = 'OPTIMISM:USDC',
  BASE_USDC = 'BASE:USDC',
  POLYGON_USDC = 'POLYGON:USDC',
  SHIB = 'ETHEREUM:SHIB',
  PEPE = 'ETHEREUM:PEPE',
  LINK = 'ETHEREUM:LINK',
  UNI = 'ETHEREUM:UNI',
  AAVE = 'ETHEREUM:AAVE',
  LN_BTC = 'LIGHTNING:BTC',
}

export interface CryptoConfig {
  network: CryptoNetwork;
  token: TokenSymbol;
  name: string;
  chainId?: number;
  isToken: boolean;
  tokenContract?: string;
  decimals: number;
  minDeposit: string;
  minWithdrawal: string;
  confirmationsRequired: number;
  averageBlockTime: number; // seconds
  derivationPath: string;
  addressRegex: RegExp;
  explorerUrl: string;
  explorerTxUrl: string;
}

/**
 * Unique key for a supported crypto (network + token combination).
 */
export type CryptoKey = string;

export function cryptoKey(network: CryptoNetwork, token: TokenSymbol): CryptoKey {
  return `${network}:${token}` as CryptoKey;
}

export const SUPPORTED_CRYPTOS: Record<string, CryptoConfig> = {
  // ── Native L1 Coins ──────────────────────────
  'BITCOIN:BTC': {
    network: CryptoNetwork.BITCOIN,
    token: TokenSymbol.BTC,
    name: 'Bitcoin',
    isToken: false,
    decimals: 8,
    minDeposit: '0.00001',
    minWithdrawal: '0.0001',
    confirmationsRequired: 3,
    averageBlockTime: 600,
    derivationPath: "m/84'/0'/0'/0",
    addressRegex: /^(bc1|[13])[a-zA-HJ-NP-Z0-9]{25,62}$/,
    explorerUrl: 'https://blockstream.info',
    explorerTxUrl: 'https://blockstream.info/tx/',
  },
  'ETHEREUM:ETH': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.ETH,
    name: 'Ethereum',
    chainId: 1,
    isToken: false,
    decimals: 18,
    minDeposit: '0.0001',
    minWithdrawal: '0.001',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'SOLANA:SOL': {
    network: CryptoNetwork.SOLANA,
    token: TokenSymbol.SOL,
    name: 'Solana',
    isToken: false,
    decimals: 9,
    minDeposit: '0.001',
    minWithdrawal: '0.01',
    confirmationsRequired: 1,
    averageBlockTime: 0.4,
    derivationPath: "m/44'/501'/0'/0'",
    addressRegex: /^[1-9A-HJ-NP-Za-km-z]{32,44}$/,
    explorerUrl: 'https://solscan.io',
    explorerTxUrl: 'https://solscan.io/tx/',
  },
  'TRON:TRX': {
    network: CryptoNetwork.TRON,
    token: TokenSymbol.TRX,
    name: 'TRON',
    isToken: false,
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 20,
    averageBlockTime: 3,
    derivationPath: "m/44'/195'/0'/0",
    addressRegex: /^T[a-zA-HJ-NP-Z0-9]{33}$/,
    explorerUrl: 'https://tronscan.org',
    explorerTxUrl: 'https://tronscan.org/#/transaction/',
  },
  'LITECOIN:LTC': {
    network: CryptoNetwork.LITECOIN,
    token: TokenSymbol.LTC,
    name: 'Litecoin',
    isToken: false,
    decimals: 8,
    minDeposit: '0.001',
    minWithdrawal: '0.01',
    confirmationsRequired: 6,
    averageBlockTime: 150,
    derivationPath: "m/84'/2'/0'/0",
    addressRegex: /^(ltc1|[LM3])[a-zA-HJ-NP-Z0-9]{25,62}$/,
    explorerUrl: 'https://blockchair.com/litecoin',
    explorerTxUrl: 'https://blockchair.com/litecoin/transaction/',
  },
  'BSC:BNB': {
    network: CryptoNetwork.BSC,
    token: TokenSymbol.BNB,
    name: 'BNB (BSC)',
    chainId: 56,
    isToken: false,
    decimals: 18,
    minDeposit: '0.001',
    minWithdrawal: '0.01',
    confirmationsRequired: 15,
    averageBlockTime: 3,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://bscscan.com',
    explorerTxUrl: 'https://bscscan.com/tx/',
  },
  'POLYGON:MATIC': {
    network: CryptoNetwork.POLYGON,
    token: TokenSymbol.MATIC,
    name: 'Polygon (MATIC)',
    chainId: 137,
    isToken: false,
    decimals: 18,
    minDeposit: '0.1',
    minWithdrawal: '1',
    confirmationsRequired: 30,
    averageBlockTime: 2,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://polygonscan.com',
    explorerTxUrl: 'https://polygonscan.com/tx/',
  },
  'AVALANCHE:AVAX': {
    network: CryptoNetwork.AVALANCHE,
    token: TokenSymbol.AVAX,
    name: 'Avalanche',
    chainId: 43114,
    isToken: false,
    decimals: 18,
    minDeposit: '0.01',
    minWithdrawal: '0.1',
    confirmationsRequired: 12,
    averageBlockTime: 2,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://snowtrace.io',
    explorerTxUrl: 'https://snowtrace.io/tx/',
  },
  'POLKADOT:DOT': {
    network: CryptoNetwork.POLKADOT,
    token: TokenSymbol.DOT,
    name: 'Polkadot',
    isToken: false,
    decimals: 10,
    minDeposit: '0.1',
    minWithdrawal: '1',
    confirmationsRequired: 12,
    averageBlockTime: 6,
    derivationPath: "m/44'/354'/0'/0",
    addressRegex: /^[1-9A-HJ-NP-Za-km-z]{47,48}$/,
    explorerUrl: 'https://polkascan.io/polkadot',
    explorerTxUrl: 'https://polkascan.io/polkadot/transaction/',
  },
  'DOGECOIN:DOGE': {
    network: CryptoNetwork.DOGECOIN,
    token: TokenSymbol.DOGE,
    name: 'Dogecoin',
    isToken: false,
    decimals: 8,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 6,
    averageBlockTime: 60,
    derivationPath: "m/44'/3'/0'/0",
    addressRegex: /^D[5-9A-HJ-NP-U][1-9A-HJ-NP-Za-km-z]{32}$/,
    explorerUrl: 'https://dogechain.info',
    explorerTxUrl: 'https://dogechain.info/tx/',
  },
  'XRPL:XRP': {
    network: CryptoNetwork.XRPL,
    token: TokenSymbol.XRP,
    name: 'XRP',
    isToken: false,
    decimals: 6,
    minDeposit: '0.1',
    minWithdrawal: '1',
    confirmationsRequired: 1,
    averageBlockTime: 4,
    derivationPath: "m/44'/144'/0'/0",
    addressRegex: /^r[1-9A-HJ-NP-Za-km-z]{24,34}$/,
    explorerUrl: 'https://xrpscan.com',
    explorerTxUrl: 'https://xrpscan.com/tx/',
  },
  'MONERO:XMR': {
    network: CryptoNetwork.MONERO,
    token: TokenSymbol.XMR,
    name: 'Monero',
    isToken: false,
    decimals: 12,
    minDeposit: '0.001',
    minWithdrawal: '0.01',
    confirmationsRequired: 10,
    averageBlockTime: 120,
    derivationPath: "m/44'/128'/0'/0",
    addressRegex: /^4[0-9AB][1-9A-HJ-NP-Za-km-z]{93}$/,
    explorerUrl: 'https://xmrchain.net',
    explorerTxUrl: 'https://xmrchain.net/tx/',
  },
  'ZCASH:ZEC': {
    network: CryptoNetwork.ZCASH,
    token: TokenSymbol.ZEC,
    name: 'Zcash',
    isToken: false,
    decimals: 8,
    minDeposit: '0.001',
    minWithdrawal: '0.01',
    confirmationsRequired: 10,
    averageBlockTime: 75,
    derivationPath: "m/44'/133'/0'/0",
    addressRegex: /^(t1|t3|zs)[a-zA-HJ-NP-Z0-9]{33,94}$/,
    explorerUrl: 'https://blockchair.com/zcash',
    explorerTxUrl: 'https://blockchair.com/zcash/transaction/',
  },
  'BITCOIN_CASH:BCH': {
    network: CryptoNetwork.BITCOIN_CASH,
    token: TokenSymbol.BCH,
    name: 'Bitcoin Cash',
    isToken: false,
    decimals: 8,
    minDeposit: '0.001',
    minWithdrawal: '0.01',
    confirmationsRequired: 6,
    averageBlockTime: 600,
    derivationPath: "m/44'/145'/0'/0",
    addressRegex: /^(bitcoincash:)?[qp][a-z0-9]{41}$/,
    explorerUrl: 'https://blockchair.com/bitcoin-cash',
    explorerTxUrl: 'https://blockchair.com/bitcoin-cash/transaction/',
  },
  'CARDANO:ADA': {
    network: CryptoNetwork.CARDANO,
    token: TokenSymbol.ADA,
    name: 'Cardano',
    isToken: false,
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '5',
    confirmationsRequired: 15,
    averageBlockTime: 20,
    derivationPath: "m/1852'/1815'/0'/0",
    addressRegex: /^addr1[a-z0-9]{58,}$/,
    explorerUrl: 'https://cardanoscan.io',
    explorerTxUrl: 'https://cardanoscan.io/transaction/',
  },

  // ── L2 / Rollup Native ───────────────────────
  'ARBITRUM:ETH': {
    network: CryptoNetwork.ARBITRUM,
    token: TokenSymbol.ETH,
    name: 'Ethereum (Arbitrum)',
    chainId: 42161,
    isToken: false,
    decimals: 18,
    minDeposit: '0.0001',
    minWithdrawal: '0.001',
    confirmationsRequired: 12,
    averageBlockTime: 0.25,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://arbiscan.io',
    explorerTxUrl: 'https://arbiscan.io/tx/',
  },
  'OPTIMISM:ETH': {
    network: CryptoNetwork.OPTIMISM,
    token: TokenSymbol.ETH,
    name: 'Ethereum (Optimism)',
    chainId: 10,
    isToken: false,
    decimals: 18,
    minDeposit: '0.0001',
    minWithdrawal: '0.001',
    confirmationsRequired: 12,
    averageBlockTime: 2,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://optimistic.etherscan.io',
    explorerTxUrl: 'https://optimistic.etherscan.io/tx/',
  },
  'BASE:ETH': {
    network: CryptoNetwork.BASE,
    token: TokenSymbol.ETH,
    name: 'Ethereum (Base)',
    chainId: 8453,
    isToken: false,
    decimals: 18,
    minDeposit: '0.0001',
    minWithdrawal: '0.001',
    confirmationsRequired: 12,
    averageBlockTime: 2,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://basescan.org',
    explorerTxUrl: 'https://basescan.org/tx/',
  },

  // ── Stablecoins & ERC-20 Tokens ──────────────
  'ETHEREUM:USDT': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.USDT,
    name: 'Tether (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0xdAC17F958D2ee523a2206206994597C13D831ec7',
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'ETHEREUM:USDC': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.USDC,
    name: 'USD Coin (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'ETHEREUM:DAI': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.DAI,
    name: 'Dai (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0x6B175474E89094C44Da98b954EedeAC495271d0F',
    decimals: 18,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'TRON:USDT': {
    network: CryptoNetwork.TRON,
    token: TokenSymbol.USDT,
    name: 'Tether (TRC-20)',
    isToken: true,
    tokenContract: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 20,
    averageBlockTime: 3,
    derivationPath: "m/44'/195'/0'/0",
    addressRegex: /^T[a-zA-HJ-NP-Z0-9]{33}$/,
    explorerUrl: 'https://tronscan.org',
    explorerTxUrl: 'https://tronscan.org/#/transaction/',
  },
  'ETHEREUM:SHIB': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.SHIB,
    name: 'Shiba Inu (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0x95aD61b0a150d79219dCF64E1E6Cc01f0B64C4cE',
    decimals: 18,
    minDeposit: '100000',
    minWithdrawal: '1000000',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'ETHEREUM:PEPE': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.PEPE,
    name: 'Pepe (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0x6982508145454Ce325dDbE47a25d4ec3d2311933',
    decimals: 18,
    minDeposit: '1000000',
    minWithdrawal: '10000000',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'ETHEREUM:LINK': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.LINK,
    name: 'Chainlink (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0x514910771AF9Ca656af840dff83E8264EcF986CA',
    decimals: 18,
    minDeposit: '0.1',
    minWithdrawal: '1',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'ETHEREUM:UNI': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.UNI,
    name: 'Uniswap (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984',
    decimals: 18,
    minDeposit: '0.1',
    minWithdrawal: '1',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },
  'ETHEREUM:AAVE': {
    network: CryptoNetwork.ETHEREUM,
    token: TokenSymbol.AAVE,
    name: 'Aave (ERC-20)',
    chainId: 1,
    isToken: true,
    tokenContract: '0x7Fc66500c84A76Ad7e9c93437bFc5Ac33E2DDaE9',
    decimals: 18,
    minDeposit: '0.01',
    minWithdrawal: '0.1',
    confirmationsRequired: 12,
    averageBlockTime: 12,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://etherscan.io',
    explorerTxUrl: 'https://etherscan.io/tx/',
  },

  // ── L2 Stablecoins ──────────────────────────
  'ARBITRUM:USDC': {
    network: CryptoNetwork.ARBITRUM,
    token: TokenSymbol.USDC,
    name: 'USDC (Arbitrum)',
    chainId: 42161,
    isToken: true,
    tokenContract: '0xaf88d065e77c8cC2239327C5EDb3A432268e5831',
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 12,
    averageBlockTime: 0.25,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://arbiscan.io',
    explorerTxUrl: 'https://arbiscan.io/tx/',
  },
  'OPTIMISM:USDC': {
    network: CryptoNetwork.OPTIMISM,
    token: TokenSymbol.USDC,
    name: 'USDC (Optimism)',
    chainId: 10,
    isToken: true,
    tokenContract: '0x0b2C639c533813f4Aa9D7837CAf62653d097Ff85',
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 12,
    averageBlockTime: 2,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://optimistic.etherscan.io',
    explorerTxUrl: 'https://optimistic.etherscan.io/tx/',
  },
  'BASE:USDC': {
    network: CryptoNetwork.BASE,
    token: TokenSymbol.USDC,
    name: 'USDC (Base)',
    chainId: 8453,
    isToken: true,
    tokenContract: '0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913',
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 12,
    averageBlockTime: 2,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://basescan.org',
    explorerTxUrl: 'https://basescan.org/tx/',
  },
  'POLYGON:USDC': {
    network: CryptoNetwork.POLYGON,
    token: TokenSymbol.USDC,
    name: 'USDC (Polygon)',
    chainId: 137,
    isToken: true,
    tokenContract: '0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359',
    decimals: 6,
    minDeposit: '1',
    minWithdrawal: '10',
    confirmationsRequired: 30,
    averageBlockTime: 2,
    derivationPath: "m/44'/60'/0'/0",
    addressRegex: /^0x[a-fA-F0-9]{40}$/,
    explorerUrl: 'https://polygonscan.com',
    explorerTxUrl: 'https://polygonscan.com/tx/',
  },

  // ── Lightning Network ────────────────────────
  'LIGHTNING:BTC': {
    network: CryptoNetwork.LIGHTNING,
    token: TokenSymbol.BTC,
    name: 'Bitcoin (Lightning)',
    isToken: false,
    decimals: 8,
    minDeposit: '0.000001',
    minWithdrawal: '0.000001',
    confirmationsRequired: 0,
    averageBlockTime: 0,
    derivationPath: "m/84'/0'/0'/0",
    addressRegex: /^ln(bc|tb)[0-9a-z]+$/i,
    explorerUrl: 'https://mempool.space/lightning',
    explorerTxUrl: 'https://mempool.space/lightning/payment/',
  },
};

export function getCryptoConfig(network: CryptoNetwork, token: TokenSymbol): CryptoConfig {
  const key = cryptoKey(network, token);
  const config = SUPPORTED_CRYPTOS[key];
  if (!config) {
    throw new Error(`Unsupported cryptocurrency: ${network}:${token}`);
  }
  return config;
}

export function isSupportedCrypto(network: string, token: string): boolean {
  const key = `${network}:${token}` as CryptoKey;
  return key in SUPPORTED_CRYPTOS;
}

export function getAllSupportedCryptos(): CryptoConfig[] {
  return Object.values(SUPPORTED_CRYPTOS);
}
